[project]
name = "history-platform"
version = "0.1.0"
description = "近代军史数智平台"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "lunar-python==1.4.8",
    "uvicorn",
    "python-multipart",
    "pydantic",
    "paddleocr==3.7.0",
    "paddlepaddle==3.3.1",
    "Pillow",
    "PyMuPDF",
]

[tool.uv]
package = false
